// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CalendarCreator: typeof import('./src/components/CalendarCreator.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCascader: typeof import('naive-ui')['NCascader']
    NDivider: typeof import('naive-ui')['NDivider']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NSpace: typeof import('naive-ui')['NSpace']
    ReceiverSelector: typeof import('./src/components/ReceiverSelector.vue')['default']
    SenderSelector: typeof import('./src/components/SenderSelector.vue')['default']
    TextInputForm: typeof import('./src/components/utils/TextInputForm.vue')['default']
    UserParser: typeof import('./src/components/utils/UserParser.vue')['default']
    UserSelector: typeof import('./src/components/UserSelector.vue')['default']
  }
}
