// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApiFetcher: typeof import('./src/components/utils/ApiFetcher.vue')['default']
    CalendarButton: typeof import('./src/components/CalendarButton.vue')['default']
    CopyrightDiv: typeof import('./src/components/CopyrightDiv.vue')['default']
    DateTimeRangePicker: typeof import('./src/components/utils/DateTimeRangePicker.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCascader: typeof import('naive-ui')['NCascader']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInput: typeof import('naive-ui')['NInput']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    ReceiverSelector: typeof import('./src/components/ReceiverSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SenderSelector: typeof import('./src/components/SenderSelector.vue')['default']
    TextInputForm: typeof import('./src/components/utils/TextInputForm.vue')['default']
    UserParser: typeof import('./src/components/utils/UserParser.vue')['default']
    UserSelector: typeof import('./src/components/UserSelector.vue')['default']
  }
}
